### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by peterhinch**
Add a reference to my uasyncio tutorial.

I'd like to add other projects. Do you prefer a single PR with multiple entries or 1 PR for each suggested addition?

### CODE REVIEW

**Comment by mcauser** [comment]
Hi @peterhinch 

You have a bunch of really great tutorials!
Single PR multiple commit, or multi PR single commit. Whatever works best for you. They are almost certainly all going to be merged :)

I thought we could even add a top level Tutorials section between Community and Books. There's plenty of good ones out there that deserve to be on the list.

**Comment by peterhinch** [comment]
> I thought we could even add a top level Tutorials section between Community and Books.

Good idea.

**Comment by mcauser** [comment]
Did you want me to merge this one, or did you have more updates?

**Comment by peterhinch** [comment]
I'll raise a new PR with the Tutorials section you suggested, plus a few other of my efforts. Hopefully in the next few days :)

**Pull request closed without merging**
