### PR TITLE
Additional Sources

### PR DESCRIPTION
**Pull request by askpatrickw**
I don't think most people know using PyPI and Libraries.io in the MP universe.

### CODE REVIEW

**Comment by mcauser** [comment]
Thanks for that. You can also find heaps on Github using the micropython topic:
https://github.com/topics/micropython
Or simply searching for repositories containing "micropython" as not everyone uses topics yet:
https://github.com/search?q=micropython

**Comment by askpatrickw** [comment]
Would you like me to add those as well?

**Comment by mcauser** [comment]
Sure, why not.

**Comment by askpatrickw** [comment]
* Added Github Topics (I didn't even know that one!)
* Github search
* Put PyPi first then alphabetical.
* Added a note about pip vs. upip

**Pull request merged**
