### PR TITLE
Updating broken link

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @mcauser 

I've noticed a broken link in the list. I've looked for the best possible replacement. I hope this works for you:

http://docs.micropython.org/en/latest/library/network.WIZNET5K.html?highlight=wiznet5k#class-wiznet5k-control-wiznet5x00-ethernet-modules

Cheers,
Peter

### CODE REVIEW

**Comment by mcauser** [comment]
Looks like it was removed in: https://github.com/micropython/micropython/commit/71dcb21e24064d1150094e66a904877402cdd157

Replaced by the submodule `lib/wiznet5k` which points to:
https://github.com/andrewleech/wiznet_ioLibrary_Driver.git

**Comment by spekulatius** [comment]
Thanks @mcauser, I just went back and updated the URL while you merged it: https://github.com/mcauser/awesome-micropython/compare/master...SpeksForks:awesome-micropython:master 

Do you want to update it?

**Comment by mcauser** [comment]
Updated in https://github.com/mcauser/awesome-micropython/pull/70

**Comment by spekulatius** [comment]
Awesome, thank you @mcauser!

**Pull request merged**
